root: true
parser: '@typescript-eslint/parser'
parserOptions:
    project:
        - './tsconfig.json'
plugins:
    - '@typescript-eslint'
    - simple-import-sort
extends:
    - eslint:all
    - plugin:@typescript-eslint/all
    - plugin:eslint-plugin/all
    - prettier
env:
    node: true
    es6: true
overrides:
    - files:
          - tests/**/*.ts
      env:
          mocha: true
rules:
    simple-import-sort/exports: 2 # Enabling the plugin simple-import-sort
    simple-import-sort/imports: 2 # Enabling the plugin simple-import-sort
    '@typescript-eslint/array-type':
        - 2
        - default: 'generic'
    one-var: 0 # Worsens the structure

    '@typescript-eslint/naming-convention': 0
    '@typescript-eslint/no-explicit-any': 0
    '@typescript-eslint/no-magic-numbers': 0
    '@typescript-eslint/no-unsafe-assignment': 0
    '@typescript-eslint/no-unsafe-call': 0
    '@typescript-eslint/no-unsafe-member-access': 0
    '@typescript-eslint/prefer-readonly-parameter-types': 0
    '@typescript-eslint/strict-boolean-expressions': 0
    line-comment-position: 0
    no-inline-comments: 0
    no-undefined: 0
