root: true
parser: '@typescript-eslint/parser'
plugins:
    - '@typescript-eslint'
    - simple-import-sort
extends:
    - eslint:all
    - plugin:@typescript-eslint/all
    - plugin:eslint-plugin/all
    - prettier
env:
    node: true
    es6: true
overrides:
    - files:
          - tests/**/*.ts
      env:
          mocha: true
rules:
    simple-import-sort/exports: 2 # Enabling the plugin simple-import-sort
    simple-import-sort/imports: 2 # Enabling the plugin simple-import-sort

    '@typescript-eslint/no-explicit-any': 0
