root: true
parser: '@typescript-eslint/parser'
plugins:
    - '@typescript-eslint'
extends:
    - eslint:recommended
    - plugin:@typescript-eslint/recommended
    - plugin:eslint-plugin/recommended
env:
    node: true
    es6: true
overrides:
    - files:
          - tests/**/*.ts
      env:
          mocha: true
rules:
    '@typescript-eslint/no-explicit-any': 0
